#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
image_serve:
    path: /images/{filename}
    controller: App\Controller\ImageController::serveImage
    requirements:
        filename: '.+\.(png|jpg|jpeg|gif)$'

