# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Mettez vos paramètres ici

services:
    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés d'événements, etc.

    # Rend les classes dans src/ disponibles pour être utilisées en tant que services
    # Cela crée un service par classe dont l'ID est le nom de la classe entièrement qualifié
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ajoutez plus de définitions de services lorsque vous avez besoin d'une configuration explicite
    # Veuillez noter que les dernières définitions remplacent toujours les précédentes

   
    # Définition du service http_client.guzzle
    Symfony\Component\HttpClient\Psr18Client: ~


   

    twilio.client:
       class: Twilio\Rest\Client
       arguments: ['%twilio_sid%', '%twilio_token%']
  
    # Ajoute un alias pour le service twilio.client
    Twilio\Rest\Client: '@twilio.client'

    App\Mailer\Weather:
        arguments:
            $httpClient: '@http_client'

    App\Mailer\MatchMailer:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
            $twig: '@twig'
